version: "3.8"

services:
  pg:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
     - "5432:5432"
